# Generated by Django 3.2 on 2022-03-20 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=10, verbose_name='name')),
                ('fullName', models.CharField(max_length=50, verbose_name='full name')),
                ('active', models.BooleanField(default=True, verbose_name='deleted')),
                ('servicePlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Companies.serviceplace')),
            ],
            options={
                'verbose_name': 'measure unit',
                'verbose_name_plural': 'measure units',
            },
        ),
        migrations.CreateModel(
            name='PackingUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('parentRatio', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='parent ratio')),
                ('active', models.BooleanField(default=True, verbose_name='deleted')),
                ('parentUnit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measureUnit', to='Dictionaries.measureunit')),
                ('servicePlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Companies.serviceplace')),
            ],
            options={
                'verbose_name': 'measure unit',
                'verbose_name_plural': 'measure units',
            },
        ),
        migrations.CreateModel(
            name='DishTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('active', models.BooleanField(default=True, verbose_name='deleted')),
                ('servicePlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Companies.serviceplace')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
    ]
