# Generated by Django 3.2 on 2022-03-15 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionariesMeasureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=10, verbose_name='name')),
                ('fullName', models.CharField(max_length=50, verbose_name='full name')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
            ],
            options={
                'verbose_name': 'measure unit',
                'verbose_name_plural': 'measure units',
            },
        ),
        migrations.CreateModel(
            name='DictionariesTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='DictionariesPackingUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('parentRatio', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='parent ratio')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('parentUnit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measureUnit', to='Dictionaries.dictionariesmeasureunit')),
            ],
            options={
                'verbose_name': 'measure unit',
                'verbose_name_plural': 'measure units',
            },
        ),
    ]
